-- ============================================================
-- Portfolio Analytics Assistant — Supabase Database Setup
-- ============================================================
-- Run this entire file once in the Supabase SQL Editor.
-- Project: MyPortfolio
-- Version: 1.0 MVP
--
-- Privacy guarantee:
--   This schema intentionally excludes fields for names,
--   email addresses, IP addresses, LinkedIn profiles,
--   Facebook profiles, or any other personally identifiable
--   information. Only anonymous, non-identifying data is stored.
-- ============================================================


-- ============================================================
-- EXTENSION
-- ============================================================
-- pgcrypto provides gen_random_uuid() on older Postgres versions.
-- Supabase 15+ includes it by default, but this ensures compatibility.
-- ============================================================

create extension if not exists "pgcrypto";


-- ============================================================
-- TABLE: page_views
-- ============================================================
-- Stores one row per page load by a non-owner visitor.
-- The client sends only the fields listed here.
-- created_at and id are generated by Supabase automatically.
-- ============================================================

create table if not exists page_views (

  -- Primary key — generated by Supabase, never sent from the browser
  id            uuid          primary key default gen_random_uuid(),

  -- Which portfolio page was loaded
  -- Expected values: 'index', 'about', 'projects', 'medicalcare'
  page          text          not null,

  -- UTM tracking parameters — all nullable (present only when visitor
  -- arrived via a UTM-tagged link, e.g. from LinkedIn or a job application)
  utm_source    text          default null,
  utm_medium    text          default null,
  utm_campaign  text          default null,

  -- Referring hostname only (e.g. 'linkedin.com', 'google.com', 'direct')
  -- Never the full referring URL — full URLs can contain tokens or profile IDs
  referrer      text          default null,

  -- True when this is the visitor's first page load of the calendar day
  -- Determined client-side using a localStorage date key
  -- Used to count unique visitors per day without a persistent user ID
  is_unique     boolean       not null default false,

  -- Anonymous, ephemeral session identifier
  -- Generated fresh each browser session (stored in sessionStorage only)
  -- Destroyed when the browser tab is closed — cannot re-identify a visitor
  -- across sessions or devices
  session_id    text          not null,

  -- UTC timestamp set automatically by Supabase on insert
  -- The client never sends this value
  created_at    timestamptz   not null default now()

);


-- ============================================================
-- INDEXES: page_views
-- ============================================================
-- created_at: used by every date-range query (today, this week, last 30 days)
-- page:       used to count views per page
-- utm_source: used to group traffic by source
-- is_unique:  used to count unique visitors efficiently
-- ============================================================

create index if not exists idx_page_views_created_at
  on page_views (created_at);

create index if not exists idx_page_views_page
  on page_views (page);

create index if not exists idx_page_views_utm_source
  on page_views (utm_source);

create index if not exists idx_page_views_is_unique
  on page_views (is_unique);


-- ============================================================
-- TABLE: click_events
-- ============================================================
-- Stores one row per tracked button or project card click
-- by a non-owner visitor.
-- ============================================================

create table if not exists click_events (

  -- Primary key — generated by Supabase, never sent from the browser
  id            uuid          primary key default gen_random_uuid(),

  -- Category of click event
  -- Expected values:
  --   'github_click'    — any link to github.com
  --   'linkedin_click'  — any link to linkedin.com
  --   'cv_download'     — any link to a .pdf file
  --   'contact_click'   — any mailto: link
  --   'project_click'   — any project card or live demo link
  event_type    text          not null,

  -- Specific target for project_click events only; null for all others
  -- Expected values: 'MedicalCare', 'VIBE Music', 'CX Agent Assist',
  --                  'TaskAi', 'TaskMan'
  target        text          default null,

  -- Which page the click happened on
  -- Expected values: 'index', 'about', 'projects', 'medicalcare'
  page          text          not null,

  -- Same session ID as the page view for this tab session
  -- Allows loose correlation between a page view and subsequent clicks
  -- within the same browser session (not across sessions)
  session_id    text          not null,

  -- UTM parameters captured at click time — mirrors the fields on page_views
  -- Allows analysis of which traffic source or campaign drove each click,
  -- not just which source drove the visit
  utm_source    text          default null,
  utm_medium    text          default null,
  utm_campaign  text          default null,

  -- Referring hostname at click time (e.g. 'linkedin.com', 'direct')
  -- Never the full URL — full URLs can contain tokens or profile IDs
  referrer      text          default null,

  -- UTC timestamp set automatically by Supabase on insert
  created_at    timestamptz   not null default now()

);


-- ============================================================
-- INDEXES: click_events
-- ============================================================
-- created_at:  used by every date-range query
-- event_type:  used to count clicks by button type
-- target:      used to count clicks per project
-- utm_source:  used to group clicks by traffic source or campaign
-- ============================================================

create index if not exists idx_click_events_created_at
  on click_events (created_at);

create index if not exists idx_click_events_event_type
  on click_events (event_type);

create index if not exists idx_click_events_target
  on click_events (target);

create index if not exists idx_click_events_utm_source
  on click_events (utm_source);


-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================
-- Enabling RLS blocks all access by default.
-- Only the policies defined below are permitted.
-- The service role (used by GitHub Actions only) bypasses RLS
-- by Supabase design and does not need explicit policies here.
-- ============================================================

alter table page_views    enable row level security;
alter table click_events  enable row level security;


-- ============================================================
-- RLS POLICIES: page_views
-- ============================================================

-- Allow anonymous visitors to INSERT rows (tracking events from the browser)
-- The anon key is safe to expose in client-side JavaScript because this
-- is the only operation it can perform on this table.
create policy "anon_insert_page_views"
  on page_views
  for insert
  to anon
  with check (true);

-- Explicitly deny anonymous SELECT
-- RLS with no SELECT policy already blocks reads, but this policy
-- makes the intent unambiguous and documents it for future maintainers.
create policy "anon_no_select_page_views"
  on page_views
  for select
  to anon
  using (false);

-- No UPDATE policy for anon — anon cannot update any row.
-- No DELETE policy for anon — anon cannot delete any row.
-- Omitting these policies is sufficient; they are blocked by default.


-- ============================================================
-- RLS POLICIES: click_events
-- ============================================================

-- Allow anonymous visitors to INSERT click event rows
create policy "anon_insert_click_events"
  on click_events
  for insert
  to anon
  with check (true);

-- Explicitly deny anonymous SELECT
create policy "anon_no_select_click_events"
  on click_events
  for select
  to anon
  using (false);

-- No UPDATE policy for anon — anon cannot update any row.
-- No DELETE policy for anon — anon cannot delete any row.


-- ============================================================
-- SETUP COMPLETE
-- ============================================================
-- After running this file, verify in Supabase:
--
-- 1. Table Editor → confirm 'page_views' and 'click_events' exist
--    with the correct columns.
--
-- 2. Authentication → Policies → confirm both tables show:
--    - RLS enabled (shield icon)
--    - Two policies each: anon INSERT allowed, anon SELECT denied
--
-- 3. Project Settings → API → copy and save:
--    - Project URL        (used in analytics.js and GitHub Actions)
--    - anon public key    (used in analytics.js only — safe to commit)
--    - service_role key   (used in GitHub Actions secrets only — never commit)
-- ============================================================
